spring.profiles.active: dev

spring:
  application:
    name: address-consumer

server:
  port: 8080

feign:
  hystrix:
    enable: false

---

spring:
  profiles: dev
  
address-provider:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8090
          
--- 

spring:
  profiles: test
  
address-provider:
  ribbon:
    eureka:
      enabled: false
    listOfServers: address-provider:8090
