spring:
  application:
    name: address-consumer

server:
  port: 8080

feign:
  hystrix:
    enable: false
  
address-producer:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8090